apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus

  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    editable: false
    jsonData:
      index:         gateway-transactions
      timeField:     timestamp
      esVersion:     "8.0.0"
      logMessageField: message
      logLevelField:   level
